### PR TITLE
NO-ISSUE: Fix image names in CI and the script to bump versions

### PR DESCRIPTION
**Pull request by rodrigonull**
Fixes image names on CI after the migration to dockerhub and also fixes the script to bump the project version.

### CODE REVIEW

**Review by jstastny-cz — APPROVED** [review]

**Comment by rodrigonull** [comment]
@ricardozanini @wmedvede Can you help us verify what could be causing the E2E tests failure?

**Review by ricardozanini — APPROVED** [review]

**Comment by ricardozanini** [comment]
@rodrigonull are the docker.io images published?

**Comment by rodrigonull** [comment]
> @rodrigonull are the docker.io images published?

yes, the images are published as you can see here:
https://hub.docker.com/r/apache/incubator-kie-sonataflow-operator/tags
https://hub.docker.com/r/apache/incubator-kie-sonataflow-builder/tags
https://hub.docker.com/r/apache/incubator-kie-sonataflow-devmode/tags

**Comment by rodrigonull** [comment]
> Is this repo part of any of our automations? I'm afraid this can cause some unwanted interference with `sonataflow-operator` currently on on `kie-tools` during the 10.0.0 release.

Yes, the nightly job is still running. I guess we need to disable it until we release 10? Or we can just disable image publishing. That is an option too.

**Comment by ricardozanini** [comment]
**After** 10.x the image publishing must be done from this repo.

**Comment by ricardozanini** [comment]
@rodrigonull can you force push to run the CI again? I

**Comment by tiagobento** [comment]
@ricardozanini Not sure why. As far as I can tell, we never agreed on moving the `kogito-swf-builder` and `kogito-swf-devmode` images from `kogito-images` to `kogito-serverless-operator.`

**Comment by ricardozanini** [comment]
@tiagobento lol, yes I meant `kogito-image`. I thought I was there.

**Comment by ricardozanini** [comment]
@rodrigonull, have you rebased this branch? I'm asking because I recently opened a PR, and e2e works perfectly.

**Comment by rodrigonull** [comment]
@ricardozanini Rebased. All green now :)

**Review by ricardozanini — APPROVED** [review]

**Pull request merged**
