### PR TITLE
kogito-serverless-operator-356: Temporary use of the nightly images

### PR DESCRIPTION
**Pull request by wmedvede**
**Description of the change:**

**Motivation for the change:**

**Checklist**

- [ ] Add or Modify a unit test for your change
- [ ] Have you verified that tall the tests are passing?

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

**Comment by wmedvede** [comment]
Hi @jordigilh , would you mind review too?

**Review by tchughesiv — CHANGES_REQUESTED** [review]
@wmedvede the label selector fixes are already being addressed in https://github.com/apache/incubator-kie-kogito-serverless-operator/pull/341 and appears ready to be merged. this PR should be limited to the nightly image change.

**Comment by wmedvede** [comment]
> @wmedvede the label selector fixes are already being addressed in #341 and appears ready to be merged. this PR should be limited to the nightly image change.

@tchughesiv  got it, I have merged #341, so now this PR is only for the temporary use of nightly images

**Review by jakubschwan — APPROVED** [review]
lgtm

**Comment by wmedvede** [comment]
@ricardozanini merging at my own risk, since now that we manage many services, I'm starting to see difficult to do working setup. I'll keep this on my radar and restore to the non nightly versions as soon as we can.

**Comment by ricardozanini** [comment]
@wmedvede can you do a follow-up PR to use https://github.com/apache/incubator-kie-kogito-serverless-operator/blob/main/version/version.go instead?

So we follow that approach, if we are on snapshot we use service nightly images.

**Pull request merged**
