### PR TITLE
incubator-kie-issues#1483: Create a common Kie Flyway initializer for Kie Modules

### PR DESCRIPTION
**Pull request by pefernan**
Closes https://github.com/apache/incubator-kie-issues/issues/1483

Ensemble: 
https://github.com/apache/incubator-kie-kogito-runtimes/pull/3672
https://github.com/apache/incubator-kie-kogito-apps/pull/2102
https://github.com/apache/incubator-kie-kogito-examples/pull/2014
https://github.com/apache/incubator-kie-kogito-serverless-operator/pull/542

**Description of the change:**

**Motivation for the change:**

**Checklist**

- [ ] Add or Modify a unit test for your change
- [ ] Have you verified that tall the tests are passing?

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

**Review by ricardozanini — COMMENTED** [review]
@pefernan, is the idea of changing the env name?

@rhkp, can you also take a look?

**Comment by pefernan** [comment]
@ricardozanini yes, the reason is that I changed the Flyway initialization of the data-index / jobs-service images. But I'm considering rolling back this change for the images. I don't want to cause any backguard incompatibility in images and operator. Tomorrow I'll try to leave the images as they were and luckily I could close this PR, leaving the operator as it is.

If we want to apply this change later, we'll have time to do it in a nother task.

**Comment by pefernan** [comment]
@ricardozanini let's catch up tomorrow about this.

**Comment by pefernan** [comment]
Rolled back the changes in the Data Index / Jobs Service images, so it will keep using the same Flyway setup. No need to change here

**Pull request closed without merging**
